server:
  port: 8084
spring:
  config:
    import: 'optional:classpath:secrets.yaml'
  application:
    name: lifeos-pathway-microservice
  datasource:
    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}
    hikari:
      connection-timeout: 20000
  jpa:
    show-sql: true
#  cloud:
#    openfeign:
#      client:
#        config:
#            default:
#                connectTimeout: 120000
#                readTimeout: 120000

