spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
  devtools:
    restart:
      enabled: false
  config:
    import: 'optional:classpath:secrets.yaml'
  application:
    name: lifeos-feed-service
  datasource:
    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}
    hikari:
      connection-timeout: 20000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8088