create table if not exists
    public.users
(
    user_id      uuid   not null,
    name         text   null,
    knowledge_xp bigint null,
    password     text   not null,
    email        text   null,
    avatar_url   text   null,
    username     text   null,
    constraint user_pkey primary key (user_id),
    constraint users_email_key unique (email),
    constraint users_username_key unique (username)
) tablespace pg_default;

create table if not exists
    public.categories
(
    name        text not null,
    slug        text null,
    category_id uuid not null,
    parent_id   uuid null,
    constraint categories_pkey primary key (category_id),
    constraint categories_parent_id_fkey foreign key (parent_id) references categories (category_id)
) tablespace pg_default;

create table if not exists
    public.feed_items
(
    item_id     uuid                     not null,
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone null,
    url         text                     null,
    title       text                     null,
    description text                     null,
    item_type   text                     null,
    user_id     uuid                     null,
    constraint FeedItem_pkey primary key (item_id),
    constraint feed_items_user_id_fkey foreign key (user_id) references users (user_id)
) tablespace pg_default;

create table if not exists
    public.article_feed_items
(
    item_id uuid not null,
    summary text null,
    content text null,
    constraint article_feed_items_pkey primary key (item_id),
    constraint article_feed_items_item_id_fkey foreign key (item_id) references feed_items (item_id) on delete cascade
) tablespace pg_default;


create table if not exists
    public.youtube_feed_items
(
    feed_id    uuid not null,
    transcript text not null,
    summary    text null,
    constraint youtube_feed_item_pkey primary key (feed_id),
    constraint youtube_feed_item_feed_id_fkey foreign key (feed_id) references feed_items (item_id) on delete cascade
) tablespace pg_default;

create table if not exists
    public.feed_item_categories
(
    feed_item_id bigint generated by default as identity not null,
    category_id  timestamp with time zone                not null default now(),
    constraint feed_item_categories_pkey primary key (feed_item_id, category_id)
) tablespace pg_default;

create table if not exists
    public.feed_item_insights
(
    insight_id   uuid not null,
    feed_item_id uuid not null,
    title        text null,
    content      text null,
    constraint feed_item_insights_pkey primary key (insight_id),
    constraint feed_item_insights_feed_item_id_fkey foreign key (feed_item_id) references feed_items (item_id) on delete cascade
) tablespace pg_default;

