import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import {
    ResizableHandle,
    ResizablePanel,
    ResizablePanelGroup,
} from "@/components/ui/resizable"

import Sidebar from "@/components/sidebar";
import {Nav} from "@/components/nav";
import {Button} from "@/components/ui/button";
import {PanelLeftClose} from "lucide-react";

const uncutsans = localFont({
    src: '../public/Uncut-Sans-v1304/Variable/UncutSans-Variable.ttf',
    display: "swap",
});

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${uncutsans.className}`}>
        <body className="flex flex-row w-full">
        <div>
            <Button variant="ghost" size="icon" className="fixed mt-2 ml-2" onClick={() => {}}>
                <PanelLeftClose className="w-8 h-8" strokeWidth={1}/>
            </Button>

        </div>
        <div className="w-full">
            <ResizablePanelGroup
                direction="horizontal"
                className="min-h-[200px]  rounded-lg border"
            >
                <ResizablePanel defaultSize={25} collapsedSize={0} minSize={15}
                                maxSize={23} collapsible={true}>
                    <div className="h-16"></div>
                    <Nav></Nav>
                </ResizablePanel>
                <ResizableHandle withHandle/>
                <ResizablePanel defaultSize={75}>
                    <div
                        className="flex h-full items-center justify-center p-6">
                        {children}
                    </div>
                </ResizablePanel>
            </ResizablePanelGroup>
        </div>
        </body>
        </html>
    );
}
