networks:
  net:
    driver: bridge
services:
  server:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8090:8000
    networks:
      - net

volumes:
  chroma-data:
    driver: local