networks:
  net:
    driver: bridge
services:
#  postgres:
#    image: ankane/pgvector:latest
#    container_name: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#    volumes:
#      - ~/postgres-volume/:/var/lib/postgresql/data
#    command: [ "postgres", "-c", "shared_preload_libraries=pg_stat_statements" ]
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#    init_pgvector:
#      image: postgres:latest
#      depends_on:
#        postgres:
#          condition: service_healthy
#      environment:
#        POSTGRES_USER: postgres
#        POSTGRES_PASSWORD: password
#      command: [ "psql", "-h", "postgres", "-U", "postgres", "-c", "CREATE EXTENSION IF NOT EXISTS vector;" ]
  server:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8090:8000
    networks:
      - net

volumes:
  chroma-data:
    driver: local