server:
  port: 8087
spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
  config:
    import: 'optional:classpath:secrets.yaml'
  application:
    name: lifeos-user-microservice
  datasource:
    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

bcrypt:
  strength: 12

jwt:
  expiration: 6000000

refreshToken:
  expirationInSeconds: 1728000